### PR TITLE
removes dependencies

### PR DESCRIPTION
**Pull request by Jascha-Sundaresan**
This removes all external dependencies. :)

prop-types works as a devDep and lodash's usage was replaced w/ Object and typeof

-----

The maintainers of this repo require that all pull request submitters adhere to the following:

- [x] I have read and will comply with the [contribution guidelines](https://github.com/FormidableLabs/freactal/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] I have read and will comply with the [code of conduct](https://github.com/FormidableLabs/freactal/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by ryan-roemer** [comment]
For server-side rendering isn't `prop-types` required? You'll get an import error if not (unless somehow the babel transformation to `lib` is removing `require("prop-types")` or something).

I've always seen it as at least a `dependencies` or `peerDependencies`.

**Comment by Jascha-Sundaresan** [comment]
My mistake. You're right.

I just confirmed w/ the prop-types documentation and they recommend leaving it as a dependency.

Rebasing my commit now.

**Comment by ryan-roemer** [comment]
LGTM.

@divmain -- You good with this one? Also looks like `maintainerd` is on the fritz again for the `body` check (?)

**Comment by stefvhuynh** [comment]
@ryan-roemer, @divmain, this LGTM.

**Comment by ryan-roemer** [comment]
LGTM. Closing and immediately reopening to kick `maintainerd` which seems on the fritz and stuck again.

**Comment by ryan-roemer** [comment]
@Jascha-Sundaresan -- Can you update to latest `master` and ping us again? Thanks!

**Comment by divmain** [comment]
I'd like to keep the `lodash` implemention of `assign` here.  Unless something has changed with recent versions of V8, the `lodash` implementation is still faster than `Object.assign`.  Same thing with `keys`.  The other removals look fine to me.

@jdalton, is this still the case?

**Comment by jdalton** [comment]
I'm 👍 on using builtin `Object.assign`.

**Comment by divmain** [comment]
Sweet, thanks JD.  I'll merge this in.

**Pull request merged**
