### PR TITLE
Remove letter "I"

### PR DESCRIPTION
**Pull request by samjbmason**
Noticed that there was a `I` character that looked like it didn't belong there.

### CODE REVIEW

**Comment by chipit24** [comment]
On the topic of spelling & grammar, the wording here should be updated as well: https://github.com/FormidableLabs/freactal#effects

> The `effects` value should be an object, where the keys are function names (**that you will later**) and the values are functions.

_... that you will later what?_

Maybe you can update your PR to fix any other spelling and grammar mistakes.

**Comment by divmain** [comment]
Going to merge this as-is.  I'll be combing through the docs to look for inconsistencies separately.

**Comment by samjbmason** [comment]
@divmain Thanks, sorry I didnt get around to tidying up any other things

**Comment by divmain** [comment]
Np :)

**Pull request merged**
