### PR TITLE
Enhancement: Add sideEffects: false to package.json

### PR DESCRIPTION
**Pull request by ryan-roemer**
`webpack@4` / `webpack@next` will support `package.json:sideEffects: false` wherein libraries can indicate their ESM re-exports are side effect free and can be much more efficiently removed for smaller, faster final bundles.

Lodash has already rolled out this change in
https://unpkg.com/lodash-es@4.17.5/package.json

## Issues

This was originally uncovered / discussed at length in:

* https://github.com/webpack/webpack/issues/1750

This PR should resolve the issues discussed in:

* https://github.com/FormidableLabs/victory/issues/549
* https://github.com/FormidableLabs/redux-little-router/issues/262

## Changes

* Add `sideEffects: false` to `package.json` to allow webpack4 tree-shaking to actually remove all unused code.

> This PR has been automatically opened by your friendly [`multibot`](https://github.com/FormidableLabs/multibot/). The transform code and documentation is available at: https://github.com/FormidableLabs/multibot-examples/tree/master/transforms/webpack-side-effects

-----

The maintainers of this repo require that all pull request submitters adhere to the following:

- [x] I have read and will comply with the [contribution guidelines](https://github.com/FormidableLabs/freactal/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] I have read and will comply with the [code of conduct](https://github.com/FormidableLabs/freactal/blob/master/CONTRIBUTE.md).
 _(required)_
- [x] All related documentation has been updated to reflect the changes made. _(required)_
- [x] My commit messages are cleaned up and ready to merge. _(required)_

The maintainers of this repository require you to select the semantic version type that
the changes in this pull request represent.  Please select one of the following:
- [ ]  major
- [ ]  minor
- [x]  patch
- [ ]  documentation only

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@divmain -- This PR was scripted, so I didn't actually do real commits from a repo. I think we can just overlook the maintainerd failures (?)

**Comment by ryan-roemer** [comment]
Also, if we can land https://github.com/FormidableLabs/freactal/pull/94 then combined with this one, webpack4 builds for this library's users should be much smaller!

**Comment by divmain** [comment]
@ryan-roemer this and changes in #94 have been published in v2.0.3.  Auto-publishing with `maintainerd` is working again, as well.

**Comment by ryan-roemer** [comment]
Lookin' good @divmain ! Thanks!

**Pull request merged**
